<?php
/**
 * Innoexts
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the InnoExts Commercial License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://innoexts.com/commercial-license-agreement
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@innoexts.com so we can send you a copy immediately.
 * 
 * @category    Innoexts
 * @package     Innoexts_Warehouse
 * @copyright   Copyright (c) 2014 Innoexts (http://www.innoexts.com)
 * @license     http://innoexts.com/commercial-license-agreement  InnoExts Commercial License
 */
?>

<!-- Warehouse -->
<?php $helper                       = Mage::helper('warehouse') ?>
<?php $taxHelper                    = $helper->getTaxHelper() ?>
<?php $config                       = $helper->getConfig() ?>
<?php $displayShippingPriceIncTax   = $taxHelper->displayShippingPriceIncludingTax() ?>
<?php $displayShippingBothPrices    = $taxHelper->displayShippingBothPrices() ?>
<!-- End Warehouse -->

<?php if ($this->getCheckout()->getStepData('shipping_method', 'complete')): ?>
<dt class="complete">
    <?php echo $this->__('Shipping Method') ?> <span class="changelink"><span class="separator">|</span> <a
        href="#shipping_method"
        onclick="checkout.changeSection('opc-shipping_method'); return false;"><?php echo $this->__('Change') ?></a></span>
</dt>
<dd class="complete">
    
    <?php /* if ($this->getShippingMethod()): ?>
        <?php echo $this->getShippingDescription() ?>

        <?php $_excl = $this->getShippingPriceExclTax(); ?>
        <?php $_incl = $this->getShippingPriceInclTax(); ?>
        <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
            <?php echo $_incl; ?>
        <?php else: ?>
            <?php echo $_excl; ?>
        <?php endif; ?>
        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
            (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
        <?php endif; ?>

    <?php else: ?>
        <?php echo $this->__('Shipping method has not been selected yet') ?>
    <?php endif; */ ?>

    <!-- Warehouse -->
    <dl class="warehouse-shipping-methods">
        <?php foreach ($this->getShippingAddresses() as $shippingAddress) : ?>
        <?php $warehouse    = $shippingAddress->getWarehouse() ?>
        <?php $stockId      = (int) $shippingAddress->getStockId() ?>
        <?php if ($config->isInformationVisible() && $warehouse) : ?>
        <dt class="warehouse">
            <span class="warehouse-name"><?php echo $this->htmlEscape($warehouse->getTitle()) ?></span>

            <?php if ($config->isOriginVisible()) : ?>
            <span class="warehouse-origin"><?php echo $this->htmlEscape($warehouse->getOriginString()) ?></span>
            <?php endif ?>

            <?php if ($config->isDistanceVisible()) : ?>
            <span class="warehouse-distance"><?php echo $this->htmlEscape($this->getCustomerAddressStockDistanceString($stockId)) ?></span>
            <?php endif ?>

            <?php if ($config->isDescriptionVisible()) : ?>
            <span class="warehouse-description"><?php echo $this->htmlEscape($warehouse->getDescription()) ?></span>
            <?php endif ?>

        </dt>
        <?php endif ?>

        <dd>
            <?php if ($shippingAddress->getShippingMethod()): ?>

                <?php echo $this->escapeHtml($shippingAddress->getShippingDescription()) ?>

                <?php $excTaxPrice = $this->formatPrice($shippingAddress->getShippingAmount()) ?>
                <?php $incTaxPrice = $this->formatPrice($shippingAddress->getShippingInclTax()) ?>

                <?php if ($displayShippingPriceIncTax): ?><?php echo $incTaxPrice ?>
                <?php else: ?><?php echo $excTaxPrice ?><?php endif ?>
                <?php if ($displayShippingBothPrices && $incTaxPrice != $excTaxPrice): ?>
                    (<?php echo $this->__('Incl. Tax') ?> <?php echo $incTaxPrice ?>)
                <?php endif ?>

            <?php else: ?>

                <?php if ($warehouse) : ?>
                <?php echo sprintf(
                    $helper->__('Shipping method has not been selected for the %s warehouse yet'), 
                    $this->escapeHtml($warehouse->getTitle())
                ) ?>
                <?php else : ?>
                <?php echo $this->__('Shipping method has not been selected yet') ?>
                <?php endif ?>

            <?php endif ?>
        </dd>
        <?php endforeach ?>
    </dl>
    <!-- End Warehouse -->
    
</dd>
<?php else: ?>
<dt>
    <?php echo $this->__('Shipping Method') ?>
</dt>
<?php endif; ?>

