<?php
/**
 * Innoexts
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the InnoExts Commercial License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://innoexts.com/commercial-license-agreement
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@innoexts.com so we can send you a copy immediately.
 * 
 * @category    Innoexts
 * @package     Innoexts_Warehouse
 * @copyright   Copyright (c) 2014 Innoexts (http://www.innoexts.com)
 * @license     http://innoexts.com/commercial-license-agreement  InnoExts Commercial License
 */
?>

<!-- Warehouse -->
<?php $helper                       = Mage::helper('warehouse') ?>
<?php $config                       = $helper->getConfig() ?>
<?php $colSpan                      = ($config->isInformationVisible()) ? 3 : 2 ?>
<!-- End Warehouse -->

<?php
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
$messages = $this->getMessages();
$_options = $this->getOptionList();
?>

<!-- Warehouse -->
<?php $productHelper                = $helper->getProductHelper() ?>
<?php $item                         = $this->getItem() ?>
<?php $itemId                       = $item->getId() ?>
<?php $product                      = $item->getProduct() ?>
<?php $buyRequest                   = $item->getBuyRequest() ?>
<!-- End Warehouse -->

<?php if ($messages): ?>
<tr class="messages">
    <td colspan="<?php echo $colSpan ?>">
        <?php foreach ($messages as $message): ?>
            <p class="item-msg <?php echo $message['type'] ?>">* <?php echo $this->escapeHtml($message['text']) ?></p>
        <?php endforeach; ?>
    </td>
</tr>
<?php endif; ?>
<tr>
    <td>

        <?php if ($this->hasProductUrl()):?>
            <a href="<?php echo $this->getProductUrl() ?>" title="<?php echo $this->escapeHtml($this->getProductName()) ?>" class="product-image"><?php endif;?><img src="<?php echo $this->getProductThumbnail()->resize(114); ?>" width="57" height="57" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /><?php if ($this->hasProductUrl()):?></a>
        <?php endif;?>

        <?php if ($isVisibleProduct && $this->getOptionList()): ?>
            <p><a class="link-edit" href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo $this->__('Edit item parameters') ?>"><?php echo $this->__('Edit') ?></a></p>
        <?php endif ?>

    </td>
    
    <!-- Warehouse -->
    <?php if ($config->isInformationVisible()) : ?>
    <td>
        
        <?php if (
            $config->isMultipleMode() && 
            $config->isAllowAdjustment() && 
            !$item->isSplitted() && 
            $productHelper->isQuoteInStock($product, $buyRequest) && 
            !$productHelper->isQuoteSingleStockIdInStock($product, $buyRequest)
        ) : ?>
        <?php $stockIds = $productHelper->getQuoteInStockStockIds($product, $buyRequest) ?>
        <select class="warehouse-select" name="cart[<?php echo $item->getId() ?>][stock_id]" title="<?php echo $helper->__('Warehouse') ?>">
            <?php foreach ($stockIds as $stockId) : ?>
            <?php $warehouse = $helper->getWarehouseByStockId($stockId) ?>
            <option value="<?php echo $warehouse->getStockId() ?>"<?php if ($stockId == $item->getStockId()) : ?> selected="selected"<?php endif; ?>><?php echo $this->htmlEscape($warehouse->getTitle()) ?></option>
            <?php endforeach; ?>
        </select>
        <?php else : ?>
        <span class="warehouse">
            <span class="warehouse-name"><?php echo $this->htmlEscape($item->getWarehouseTitle()) ?></span>
        </span>
        <?php endif; ?>
        
        <?php if (
            $config->isCatalogInformationVisible() && 
            $productHelper->isQuoteInStock($product, $buyRequest)
        ) : ?>
        
        <span class="cart-item-product-quote-button" onclick="toggleWarehouses(this, 'cart-item-product-quote-<?php echo $itemId ?>')">
            <span class="collapsed" style="white-space:nowrap;"><a href="javascript: function returnFalse() { return false; }"><?php echo $helper->__('Show Details') ?></a></span>
            <span class="expanded" style="display:none;white-space:nowrap;"><a href="javascript: function returnFalse() { return false; }"><?php echo $helper->__('Hide Details') ?></a></span>
        </span>
        
        <?php endif ?>
        
    </td>
    <?php endif ?>
    <!-- End Warehouse -->

    <td>

        <a href="<?php echo $this->getDeleteUrl()?>" title="<?php echo $this->__('Remove item')?>" class="btn-remove btn-remove2"><?php echo $this->__('Remove item')?></a>

        <h2 class="product-name">
        <?php if ($this->hasProductUrl()):?>
            <a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->escapeHtml($this->getProductName()) ?></a>
        <?php else: ?>
            <?php echo $this->escapeHtml($this->getProductName()) ?>
        <?php endif; ?>
        </h2>

        <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock): ?>
            <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif;?>

        <div class="price-box">

            <div class="qty-wrap">
                <input name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" size="4" title="<?php echo $this->__('Qty') ?>" class="input-text qty" maxlength="12" />
                <span<?php if ($this->getQty() == 1) echo ' style="display:none;"' ?>>×</span>
            </div>

            <div class="cart-price-box"<?php if ($this->getQty() == 1) echo ' style="display:none;"' ?>>

                <?php if ($canApplyMsrp): ?>
                    <span class="cart-price">
                        <span class="cart-msrp-unit"><?php echo $this->__('See price before order confirmation.'); ?></span>
                        <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                        <a id="<?php echo $helpLinkId ?>" href="#" class="map-help-link"><?php echo $this->__("What's this?"); ?></a>
                        <script type="text/javascript">
                            Catalog.Map.addHelpLink($('<?php echo $helpLinkId ?>'), "<?php echo $this->__("What's this?") ?>");
                        </script>
                    </span>
                <?php else: ?>

                    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>

                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                        <?php else: ?>
                            <span class="cart-price">
                        <?php endif; ?>
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
                            <?php else: ?>
                                <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
                            <?php endif; ?>

                        </span>


                        <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                            <div class="cart-tax-info" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </div>

                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                    <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>

                    <?php endif; ?>
                    <?php if ($this->helper('tax')->displayCartPriceInclTax()): ?>

                        <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                        <?php else: ?>
                            <span class="cart-price">
                        <?php endif; ?>

                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
                            <?php else: ?>
                                <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
                            <?php endif; ?>

                        </span>
                        <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                            <div class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </div>

                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                    <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?></span>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>

                    <?php endif; ?>
                <?php endif; ?>

            </div>

            <div class="cart-price-box">

                <?php if ($this->helper('tax')->displayCartPriceExclTax() && !$_item->getNoSubtotal()): ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <?php else: ?>
                        <span class="cart-price">
                    <?php endif; ?>

                        <?php if ($canApplyMsrp): ?>
                            <span class="cart-msrp-subtotal">--</span>
                        <?php else: ?>
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
                            <?php else: ?>
                                <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
                            <?php endif; ?>
                        <?php endif; ?>

                    </span>
                    <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                        <div class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>

                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>

                <?php endif; ?>

                <?php if (($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>

                    <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <?php else: ?>
                        <span class="cart-price">
                    <?php endif; ?>

                        <?php if ($canApplyMsrp): ?>
                            <span class="cart-msrp-subtotal">--</span>
                        <?php else: ?>
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
                            <?php else: ?>
                                <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
                            <?php endif; ?>
                        <?php endif; ?>

                    </span>


                    <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                        <div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>

                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?></span>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>

                <?php endif; ?>

            </div>

        </div>

    </td>
</tr>
<?php if ($_options):?>
<tr class="product-options">
    <td colspan="<?php echo $colSpan ?>">
        <span class="toggle" onclick="$(this).next('.product-options').toggle(); return false;">Show Options</span>
        <div class="product-options" style="display:none;">
            <dl class="item-options">
                <?php foreach ($_options as $_option) : ?>
                    <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                    <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                        <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                    <?php else: ?>
                        <dd><?php echo $_formatedOptionValue['value'] ?></dd>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
        </div>
    </td>
</tr>
<?php endif;?>

<!-- Warehouse -->

<?php if (
    $config->isCatalogInformationVisible() && 
    $productHelper->isQuoteInStock($product, $buyRequest)
) : ?>

<?php $store                        = $product->getStore() ?>
<?php $shippingHelper               = $helper->getShippingHelper() ?>
<?php $quoteHelper                  = $helper->getQuoteHelper() ?>
<?php $taxHelper                    = $helper->getTaxHelper() ?>
<?php $displayShippingPriceIncTax   = $taxHelper->displayShippingPriceIncludingTax() ?>
<?php $displayShippingBothPrices    = $taxHelper->displayShippingBothPrices() ?>
<?php $currentStockId               = $productHelper->getCurrentStockId($product) ?>

<?php if (!$config->isCatalogOutOfStockVisible()) : ?>
<?php $stockIds = $productHelper->getQuoteInStockStockIds($product, $buyRequest) ?>
<?php else : ?>
<?php $stockIds = $helper->getStockIds() ?>
<?php endif ?>

<tr id="cart-item-product-quote-<?php echo $itemId ?>" style="display:none;">
    <td colspan="<?php echo $colSpan ?>" class="a-center">
        <table class="data-table product-quote">
            
            <col />

            <?php if ($config->isCatalogAvailabilityVisible()) : ?>
            <col width="65" />
            <?php endif ?>

            <?php if ($config->isCatalogQtyVisible()) : ?>
            <col width="50" />
            <?php endif ?>

            <col width="80" />

            <?php if ($config->isCatalogTaxVisible()) : ?>
            <col width="80" />
            <?php endif ?>

            <?php if (
                $config->isCatalogShippingVisible() && 
                !$productHelper->isVirtual($product) && 
                !$productHelper->isDownloadable($product)
            ) : ?>
            <col width="225" />
            <?php endif ?>
        
            <thead>
                <tr>

                    <th><?php echo $helper->__('Warehouse') ?></th>

                    <?php if ($config->isCatalogAvailabilityVisible()) : ?>
                    <th><?php echo $helper->__('In Stock') ?></th>
                    <?php endif ?>

                    <?php if ($config->isCatalogQtyVisible()) : ?>
                    <th><?php echo $helper->__('Qty') ?></th>
                    <?php endif ?>

                    <th><?php echo $helper->__('Subtotal') ?></th>

                    <?php if ($config->isCatalogTaxVisible()) : ?>
                    <th><?php echo $helper->__('Tax') ?></th>
                    <?php endif ?>

                    <?php if (
                        $config->isCatalogShippingVisible() && 
                        !$productHelper->isVirtual($product) && 
                        !$productHelper->isDownloadable($product)
                    ) : ?>
                    <th><?php echo $helper->__('Shipping') ?></th>
                    <?php endif ?>

                </tr>
            </thead>
            <tbody>
                
                <?php foreach ($stockIds as $stockId) : ?>
                
                <?php $warehouse = $helper->getWarehouseByStockId($stockId) ?>
                
                <tr class="warehouse<?php if ($currentStockId == $stockId) : ?> current<?php endif ?>">

                    <td>
                        <span class="warehouse-name"><?php echo $this->htmlEscape($warehouse->getTitle()) ?></span>
                    
                        <?php if ($config->isCatalogOriginVisible()) : ?>
                        <span class="warehouse-origin"><?php echo $this->htmlEscape($warehouse->getOriginString()) ?></span>
                        <?php endif ?>
                        
                        <?php if ($config->isCatalogDistanceVisible()) : ?>
                        <span class="warehouse-distance"><?php echo $this->htmlEscape($helper->getCustomerAddressStockDistanceString($stockId)) ?></span>
                        <?php endif ?>

                        <?php if ($config->isCatalogDescriptionVisible()) : ?>
                        <span class="warehouse-description"><?php echo $this->htmlEscape($warehouse->getDescription()) ?></span>
                        <?php endif ?>

                    </td>

                    <?php if ($config->isCatalogAvailabilityVisible()) : ?>
                    <?php $isInStock = $productHelper->getQuoteIsInStock($product, $stockId, $buyRequest) ?>
                    <td class="a-center"><?php echo ($isInStock) ? $helper->__('Yes') : $helper->__('No') ?></td>
                    <?php endif ?>

                    <?php if ($config->isCatalogQtyVisible()) : ?>
                    <?php $isInStock = $productHelper->getQuoteIsInStock($product, $stockId, $buyRequest) ?>
                    <?php $qty = $productHelper->getQuoteMaxQty($product, $stockId, $buyRequest) ?>
                    <td><?php echo ($isInStock && ($qty > 0)) ? $qty : 0 ?></td>
                    <?php endif; ?>

                    <?php $price = $productHelper->getQuoteSubtotal($product, $stockId, $buyRequest) ?>
                    <td class="a-center"><?php echo $store->formatPrice($price, false) ?></td>

                    <?php if ($config->isCatalogTaxVisible()) : ?>
                    <?php $taxAmount = $productHelper->getQuoteTaxAmount($product, $stockId, $buyRequest) ?>
                    <td class="a-center"><?php echo $store->formatPrice($taxAmount, false) ?></td>
                    <?php endif ?>

                    <?php if (
                        $config->isCatalogShippingVisible() && 
                        !$productHelper->isVirtual($product) && 
                        !$productHelper->isDownloadable($product)
                    ) : ?>
                    <?php $shippingRates = $quoteHelper->getGroupedShippingRates(
                        $productHelper->getQuote($product, $stockId, $buyRequest)
                    ) ?>
                    <td>
                        <?php if (count($shippingRates)) : ?>
                        <dl class="sp-methods warehouse-shipping-methods shipping-methods">
                            <?php foreach ($shippingRates as $carrierCode => $carrierShippingRates): ?>
                            <dt><?php echo $this->escapeHtml($shippingHelper->getCarrierName($carrierCode)) ?></dt>
                            <dd>
                                <ul>
                                    <?php foreach ($carrierShippingRates as $rate): ?>
                                    <li>
                                    <?php if ($rate->getErrorMessage()): ?>
                                    <ul class="messages">
                                        <li class="error-msg">
                                            <ul><li><?php echo $this->escapeHtml($rate->getErrorMessage()) ?></li></ul>
                                        </li>
                                    </ul>
                                    <?php else: ?>
                                    <?php echo $this->escapeHtml($rate->getMethodTitle()) ?>
                                    <?php $priceExcTax = $rate->getPriceExcTax() ?>
                                    <?php $priceIncTax = $rate->getPriceIncTax() ?>
                                    <?php if (!$displayShippingPriceIncTax) : ?>
                                    <?php echo $store->convertPrice($priceExcTax, true, false) ?>
                                    <?php else : ?>
                                    <?php echo $store->convertPrice($priceIncTax, true, false) ?>
                                    <?php endif ?>
                                    <?php if ($displayShippingBothPrices && $priceIncTax != $priceExcTax): ?>
                                    (<?php echo $helper->__('Incl. Tax') ?> <?php echo $store->convertPrice($priceIncTax, true, false) ?>)
                                    <?php endif ?>
                                    <?php endif ?>
                                    </li>
                                    <?php endforeach ?>
                                </ul>
                            </dd>
                            <?php endforeach ?>
                        </dl>
                        <?php else : ?>
                        <p><?php echo sprintf($helper->__('There are no shipping methods available.')) ?></p>
                        <?php endif ?>
                    </td>
                    <?php endif ?>

                </tr>

                <?php endforeach ?>
            </tbody>
            
        </table>
        
    </td>
</tr>

<?php endif ?>

<!-- End Warehouse -->